### ISSUE TITLE
Add 'folders' domain, action and route.

### ISSUE THREAD

**Issue by tertek** [Research-IT-Swiss-TPH/pdf-form-filling-api#15]
- [x] Open a new branch based on dev  named "add-folders"
- [x] Add database structure based on ERD
- [x] Add database seeder (Slim Book!)
- [x] Implement domain/folder/[Repository|Service|Data]
- [x] Implement actions
- [x] Implement routes
- [x] Add http/folders requests for all routes

**Comment by tertek** [comment]
@edenst-TPH 

Da seit neuster Version des ERD "Projects" in "Folders" umbenannt wurde, muss hier nat¨ürlich auch entsprechend angepasst werden.

**Comment by edenst-TPH** [comment]
- [] new git branch "add-Folders" (after resync dev from server dev branch)
- []"Folder" dir  & file structure in "Action"/ & "Domain"/, class & method names
- []adapted: Domain/Folder/Service/FolderValidator.php

**Comment by tertek** [comment]
Nachdem obige Liste abgeschlossen ist, gilt es wie heute besprochen:

- [ ] branch in dev mergen
- [ ] PR auf SwissTPH  dev branch erstellen
- [ ] Fork-git-flow aufheben

**Comment by tertek** [comment]
Zwei Anmerkungen:

1. Die commit message  "features and db migrations of domain add-Folders are afaik complete; testing with http files does not yet work"
ist zu lange bzw. beinhaltet Informationen die meiner Meinung nach nicht in den Commit passen. Die commit Nachricht sollte so kurz und objektiv wie möglich sein. Aussagen über das Gesamtsystem sind nicht passend, solang es nicht durch den Commit direkt beeinflusst wird. Deshalb reicht hier als message:
"added features and improved DB migrations"

2. git rebase dev sollte vor dem committen ausgeführt werden, sodass es auch Teil des Commits ist. Dann wird der Fehler  error: refused "local is behind" wohl auch nicht angezeigt

**Comment by tertek** [comment]
Added in https://github.com/Research-IT-Swiss-TPH/pdf-form-filling-api/pull/19
