### ISSUE TITLE
Add documents domain, action and route.

### ISSUE THREAD

**Issue by tertek** [Research-IT-Swiss-TPH/pdf-form-filling-api#20]
As with folder domain, add documents domain.

Additional tasks: 
- add PDfFactory including php-pdftk.

**Comment by edenst-TPH** [comment]
When the documents entity can be merged, I see 2 possible continuations: 
- complete the documents with versions incl pdf handling (with or without pdf-factory)
- redo customers feature so that programming and migration / seed match the erd; also handle created / updated timestamps

**Comment by tertek** [comment]
as discussed, we will move fields from versions table into documents. Please adjust accordingly.
