### ISSUE TITLE
Add jobs domain, action and route.

### ISSUE THREAD

**Issue by tertek** [Research-IT-Swiss-TPH/pdf-form-filling-api#33]
@edenst-TPH Do you need any more info on this to start?

**Comment by edenst-TPH** [comment]
Resolutions of the meeting Ekin / Stephan 2024-05-16
Endpoint "createJob" will be extended to include validations
1. We expect a user token, document_id, and payload data in specific json format: name-value
2. Token-User authorized?
3. Record count ( = number of pdfs to create) within user quota?
4. Does the first record fit the fields found in the pdf? Every supplied field must match a pdf field by name
5. Do all supplied have the same fields?
