### ISSUE TITLE
Use Case Diagram

### ISSUE THREAD

**Issue by tertek** [Research-IT-Swiss-TPH/pdf-form-filling-api#6]

**Comment by edenst-TPH** [comment]
User Interaktionen, summarisch
Source: https://github.com/Research-IT-Swiss-TPH/pdf-api/blob/master/docs/pdfapi-interact_04.drawio


![pdfapi-interact_04 drawio](https://github.com/Research-IT-Swiss-TPH/pdf-api/assets/148859848/e951f54d-5422-4c81-8655-94e6c6a5d2d0)

**Comment by tertek** [comment]
Die Interaktionen sind nicht korrekt.

Das Projekt wird vorher erstellt. Kann initial bei der Erstellung für den Customer erstellt werden.

Das Dokument wird in einem Projekt hochgeladen.

Nach dem Hochladen des Dokuments, wird es validiert, sowie gescannt, dh. die field names werden gespeichert für die document_id.

**Comment by tertek** [comment]
This has to be redone.
Closing to be opened as new issue.
